name: raw_microservices
description: A simple command-line application.
version: 1.0.0

publish: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  #path: ^1.8.0
  mailjet: ^1.0.3+3
  power_plant: ^1.0.0+1
  dbx_platform: ^1.1.5+7
  
dev_dependencies:
  lints: ^1.0.0
